NF: read segmentation data from fda files
marksgraham/OCT-Converter pull request #95
Opened 2023-03-08 16:12 UTC by drombas

Closes #94 

Changes
- Add a `read_segmentation` method to FDA class
- Update fda example

Comments
- I had to change the chunk listing to store the position of all @CONTOURINFO chunks as a list
- I have noticed that OCTVolumeWithMetaData class supports contour information. Maybe for a next PR?

Happy to make any changes if needed.

2023-03-08 17:10 UTC, marksgraham commented
Hi @drombas 

Thanks for this! I'm snowed under with a conference deadline until Friday, so I'll take a proper look at it then. 

You're right, there is a contours part of OCTVolume, storing it there would make viewing them easily compatible with the `peek` method as we've done for e2e [here](https://github.com/marksgraham/OCT-Converter/blob/main/examples/demo_e2e_extraction.py), which would be nice! But we can save for another PR.

2023-03-13 16:46 UTC, marksgraham requested changes
Hey, looks great! 

It looks like its easy to get this compatible with the `OCTVolume` contours field. Would you be able to add this to the `read_oct_volume` method?

```
        # read segmentation contours and store in OCTVolume, if possible
        contours = self.read_segmentation()
        if contours:
            # define as distance from top of scan to make compatible with plotting in OCTVolume
            image_height = volume[:, :, i].shape[0]
            contours = {k:image_height - v for k,v in contours.items()}
        oct_volume.contours = contours
        return oct_volume
```

One that is done we can update the example with `oct_volume.peek(show_contours=True)` and get out something like this:

![image](https://user-images.githubusercontent.com/7947315/224768938-7b3790f3-9914-40d5-ad76-188af1931971.png)

This requires the layers to be defined from the top of the b-scan, rather than bottom, to stay consistent with how it is done in the E2E class. I propose we leave the `read_segmentation` function as is and do the transformation before it gets stored in the OCTVolume, allowing you to get contours defined from the bottom for compatibility with `eyepy`

2023-03-13 16:46 UTC, marksgraham commented on oct_converter/readers/fda.py
> +        """
Please could you change to the following to make compatible with the other docstrings:

```
        Returns
            dict: dictionary with segmentation data.
```

2023-03-14 07:19 UTC, drombas commented
Hi @marksgraham. Thanks a lot for your feedback. 

I've made the changes. I took the liberty of simplifying the code a bit but feel free to request any changes.

2023-03-14 14:52 UTC, marksgraham approved these changes
Looks great :)

2023-03-14 14:56 UTC, merged